// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailValidator is an autogenerated mock type for the EmailValidator type
type EmailValidator struct {
	mock.Mock
}

// IsValid provides a mock function with given fields: email
func (_m *EmailValidator) IsValid(email string) bool {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewEmailValidator creates a new instance of EmailValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailValidator {
	mock := &EmailValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
